/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC;
-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_key) DESC;
-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_key) DESC;
-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC;
-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(s.sales_amount) AS total_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY SUM(s.sales_amount) DESC;
-- Find total revenue is generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_sales
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY SUM(s.sales_amount) DESC;
-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(s.quantity)  AS total_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY country
ORDER BY SUM(s.quantity) DESC;
